[package]
name = "io_uring_test"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[[bin]]
name = "io_uring_test"
path = "src/main.rs"

[dependencies]
libuser = { path = "../../libuser" }

[profile.release]
opt-level = "z"
lto = true
