[package]
name = "libuser"
version = "0.1.0"
edition = "2024"
license = "MIT"
license-file = "LICENSE"

[lib]
name = "libuser"
path = "src/lib.rs"

[dependencies]
# Shared ABI definitions
rany_os_abi = { path = "../rany_os_abi", features = ["userspace"] }
