[package]
name = "builder"
version = "0.1.0"
edition = "2021"
license = "MIT"
license-file = "LICENSE"

[workspace]

[dependencies]
bootloader = { version = "=0.11.10", default-features = false, features = ["uefi"] }

[[bin]]
name = "builder"
path = "src/main.rs"
