[package]
name = "builder"
version = "0.1.0"
edition = "2021"
license = "MIT"
license-file = "LICENSE"

[dependencies]
bootloader = "0.11.12"

[[bin]]
name = "builder"
path = "src/main.rs"

# Empty workspace to make this package independent from parent workspace
[workspace]
